local Moist_Translate = {lang = "DE"}

function Moist_Translate.localmenu(feat)
	
Features.LocalParent.name = "Feuchter Skript ng"
LocalFeatures["Self_Parent"].name = "Spielerfunktionen"
LocalFeatures["Online_Parent"].name = "Online - Funktionen"
LocalFeatures["History"].name = "Spielergeschichte"
LocalFeatures["Session_Griefing"].name = "Sitzung Trauer"
LocalFeatures["World_Parent"].name = "Weltmerkmale"
LocalFeatures["UI_Parent"].name = "UI -Funktionen"
Features["EntityTools"].name = "Entity Functions & Tools"
Features["Tests"].name = "Funktionen Tests"
LocalFeatures["Stats"].name = "STAT -Funktionen"
LocalFeatures["Self_WeaponStuff"].name = "Waffenbezogene Funktionen"
LocalFeatures["PortableDefences"].name = "Tragbare Verteidigungskugel"
LocalFeatures["Self_Ped"].name = "Spieler Ped -Funktionen"
LocalFeatures["Self_Veh"].name = "Spielerfahrzeug -Merkmale"
LocalFeatures.CargoBobMod.name = "CargoBob Mod"
LocalFeatures.TrainControl.name = "Feuchter trainieren Mod"
Features.ScriptLoader.name = "Feuchterskript Skript Loader"
Features.LocalSettings.name = "Feuchte Skripteinstellungen"
LocalFeatures["save_settings"].name = "Aktuelle Einstellungen: "
LocalFeatures["HotKeyParent"].name = "Feuchte Drehbuch -Hotkeys"
LocalFeatures["SaveOptions_Hotkey"].name = "Optionen speichern Hotkey"
Features.LocalModules.name = "Laden Sie feuchte Skriptmodule"
LocalFeatures["Translate"].name = "Das Skript mit Übersetzung aktualisieren"
LocalFeatures["Send_All_To_Beach"].name = "Senden Sie alles an Del Pero : "
LocalFeatures["stringstatset"].name = "Setzen Sie stat: "
LocalFeatures.wetnessframe.name = "Machen Sie meinen Charakter, nass! :P"
LocalFeatures.GhostMyself.name = "Setzen Sie mich selbst, geistert anderen Spielern"
LocalFeatures.Turbulance.name = "Flugzeugturbulenzen"
LocalFeatures.AirDrag.name = "Set Air Drag Multiplier: "
LocalFeatures["AltLvl"].name = "Altitude Level Indication: "
LocalFeatures["WindSpeed"].name = "Set Wind Speed: "
LocalFeatures.Aileron.name = "Disable Plane Aileron"
LocalFeatures.VehDamageProof.name = "Set Vehicle Damage Proof"
LocalFeatures.VehEngAudioMod.name = "Engine Audio: "
LocalFeatures["Enable_Trains2"].name = "Enable Train Spawning"
LocalFeatures["Track_Switch"].name = "Track Switch"
LocalFeatures["Train_Control"].name = "Train Control"
LocalFeatures["Train_Direction"].name = "Switch Train Spawn Direction"
LocalFeatures["Train_Spawn"].name = "Spawn Train Variation: "
LocalFeatures["Train_Cruise"].name = "Train Cruise: "
LocalFeatures["Train_speed"].name = "Train Speed: "
LocalFeatures["Train_stop"].name = "Stop Train"
Train_Control_Meter1.name = "Control Speed(Instant Insane Speed)"
Train_Control_Meter2.name = "Control Input Cruise Speed"
Train_Control_Meter3.name = "Control Meter"
Train_Control_Brake.name = "Control Input Handbrake"
Train_Derailed.name = "DeRail Train"
LocalFeatures.CbobMagnet.name = "CargoBob: "
LocalFeatures["CbobMagMod1"].name = "Magnet Pickup Strength: "
LocalFeatures["CbobMagMod2"].name = "Magnet Effect Radius: "
LocalFeatures["CbobMagMod3"].name = "Magnet Pull Rope Length: "
LocalFeatures["CbobMagMod4"].name = "Magnet Rope Length: "
LocalFeatures["CbobMagMod5"].name = "Magnet Pull Strength: "
LocalFeatures.IAMACOP.name = "Turn Me into a Cop (Cops Act like you are!)"
LocalFeatures.UlWeClip.name = "Weapon Clip: "
LocalFeatures["WeapExpRad"].name = "Explosion Multiplier"
LocalFeatures.Lightning.name = "LightningBolt Generator: "
LocalFeatures["RainLvl"].name = "Set Rain Level:  "
LocalFeatures.WaterOverStg.name = "Water Override Strength:  "
LocalFeatures.WaterMod.name = "Modify Water Radius:  "
LocalFeatures.RippleDis.name = "Water Ripple Disturbance:  "
LocalFeatures.RippleBump.name = "Water Ripple Bumpiness:  "
LocalFeatures.ShoreWaveAmp.name = "Override ShoreWave Amplitude:  "
LocalFeatures.RiotMode.name = "Turn ON Riot Mode!"
LocalFeatures.Projectiles.name = "Destroy Projectiles(WIP)"
LocalFeatures.ProjectilesV2.name = "Remove Projectiles"
LocalFeatures.DefenceManualRAD.name = "Set Below Values Manually"
LocalFeatures.AirDefence.name = "Player Vehicle"
LocalFeatures.AirDefence2.name = "Player Ped"
LocalFeatures.AirDefence3.name = "Anti Projectile"
LocalFeatures.AirDefence4.name = "WayPoint Anti Player Ped"
LocalFeatures.setDefenceZone.name = "Zone Flags for: "
LocalFeatures.BigMapMod.name = "Minimap View Mode: "
LocalFeatures.PlayerBlipEnhanced.name = "Blip Enhancements Cone & Heading"
LocalFeatures.PlayerBlipEnhanced2.name = "Blip Enhancements Height"
LocalFeatures.PlayerBlipOTR.name = "OTR Player Blips"
LocalFeatures.RemAllAirDef.name = "Remove All Air Defence Zone"
LocalFeatures.RadarZoom.name = "Set Radar Zoom: "
LocalFeatures["ScriptSafe"].name = "ScriptEvent SafeMode"
LocalFeatures["AutoScriptHost"].name = "Auto Take ScriptHost"
LocalFeatures["PlayerKiller"].name = "Get Player Killers"
LocalFeatures["NotifiedReset"].name = "Player Notification Reset"
LocalFeatures["GodPlayerNotif"].name = "God Mode Player Notify"
LocalFeatures["DamageProofPlayerNotif"].name = "Damage Proof Player Notify"
LocalFeatures["DetectPlayerRC"]["name"] = "Enable RC Vehicle Detection"
LocalFeatures["MissileDetection"]["name"] = "Enable Sub Missile Detection"
LocalFeatures["SessionLog"]["name"] = "Log Session Joins"	
FeaturesModulelists.name = "Custom Lists for Features"
FeaturesModules_PlayerHistory.name = "Load PlayerHistory Module"
FeaturesModules_PlayerBar.name = "Load PlayerBar Module"
FeaturesModules_Translate.name = "Load Translation Module"
FeaturesModules_NetEvents.name = "Load Network Events Module"
FeaturesModules_ESP.name = "Load ESP Module"
FeaturesModules_LuaLoader.name = "Load Script Loader Module"
FeaturesModules_Pedlist.name = "Load Ped List"
FeaturesModules_Vehlist.name = "Load Vehicle List"
LocalFeatures.NoRsEditorRec.name = "Disable R*Editor Recording"

	
	
end


function Moist_Translate.onlinemenu(feat)
	
	for pid = 0, 31 do
FeaturesonlineParent.feats[pid].name = "Moist Script NG"
Features.RemovePlayer.feats[pid].name = "Remove Player"
Features.PlayerOptions.feats[pid].name = "Player Options"
Features.PlayerExclusion.feats[pid].name = "Player Exclusion"
OnlineFeats.PlayerWaypoint.feats[pid].name = "Player Waypoint"
OnlineFeats.PlayerGhosting.feats[pid].name = "Ghost Myself To Player"
Features.PlayerInfo.feats[pid].name = "Player Info"
Features.PlayerIPInfo.feats[pid].name = "Player IP Info"
Features.Troll.feats[pid].name = "Troll & Annoy"
Features.GriefThisCunt.feats[pid].name = "Grief This Cunt ! !"
Features.FramePlayer.feats[pid].name = "Grief Others (Frame Player)"
Features.ScriptEvents.feats[pid].name = "Script Events"
Features["CEO"].feats[pid].name = "CEO Features"
OnlineFeats["FramedSessionOrbital"].feats[pid].name = "Framed Session Orbital Strike"
OnlineFeats["FramedOrbital"].feats[pid].name = "Orbital Player: "
OnlineFeatures["Beach_War"].feats[pid].name = "Send All Others to Beach"
OnlineFeatures["CuntCannon"].feats[pid].name = "Kill with: "
OnlineFeatures["NBV_RAM2"].feats[pid].name = "Nearby Vehicles: "
OnlineFeats["AVERAGE_LATENCY"].feats[pid].name = "Latency Test"
OnlineFeats["GetZoneInfo"].feats[pid].name = "Get Player Zone Info"
OnlineFeats["GetInfo"].feats[pid].name = "Get Info"
OnlineFeats["Toggle_NetStats"].feats[pid].name = "Toggle On Net Stats"
OnlineFeats["ACKS"].feats[pid].name = "unAck TX's: "
OnlineFeats["UnrelResend"].feats[pid].name = "Unreliable Resend Count: "
OnlineFeats["Latency"].feats[pid].name = "Latency (ms): "
OnlineFeats["PacketLoss"].feats[pid].name = "PacketLoss : "
OnlineFeats["SetMiniMap2Player"].feats[pid].name = "Set Minimap to Players Location"
OnlineFeats["SetMiniMap2PlayerBlip"].feats[pid].name = "Minimap Zoom to Players Blip"
OnlineFeats["SetMiniMap2PlayerBlip"].feats[pid].name = "Minimap Zoom to Players Blip"
OnlineFeats["UnlockMinimapZoom"].feats[pid].name = "Unlock Minimap Zoom"
OnlineFeats["SetPlayerBlipFlash"].feats[pid].name = "Players Blip Flashes"
OnlineFeats["NetworkBail"].feats[pid].name = "Network Bail Kick"
OnlineFeats["ErrorKick"].feats[pid].name = "Micheal Error Kick"
OnlineFeats["NetworkBail"].feats[pid].name = "Force Error Kick"
OnlineFeatures["CEOMoney"].feats[pid].name = "Loop Payment: "
OnlineFeatures["REM_CEO"].feats[pid].name = "Remove CEO: "
OnlineFeatures["SendCops"].feats[pid].name = "Dispatch Cops to Player Location"
OnlineFeatures["FuelLeak"].feats[pid].name = "Players Vehicle Leaks Fuel"
OnlineFeatures["GangHarrasment"].feats[pid].name = "Gangs will Hassle Player"
OnlineFeatures["InvSpam"].feats[pid].name = "Spam Invites"
OnlineFeatures["GangGrief"].feats[pid].name = "Gangs will Grief Player"
OnlineFeatures["DisablePlayerInterior"].feats[pid].name = "Disable Player Interior"
OnlineFeatures["OTR"].feats[pid].name = "Off The Radar"
OnlineFeatures["NOCOPS"].feats[pid].name = "Cops Turn a Blind Eye"
OnlineFeatures["SE_Crash"].feats[pid].name = "Send Event: "
OnlineFeatures["SE_CrashV2"].feats[pid].name = "Send Event V.2: "
OnlineFeatures["SE_CrashV3"].feats[pid].name = "Send Event V.3: "
OnlineFeatures["VehSyncCrash"].feats[pid].name = "Lester Cummy WindSock Crash"
OnlineFeatures["VehSyncCrashV2"].feats[pid].name = "Lester Cummy WindSock Crash"
OnlineFeatures["VehSyncCrash2"].feats[pid].name = "Use Ruiner Crash & Bail to Space"
OnlineFeatures["Island_Events"].feats[pid].name = "Island Events: "
OnlineFeatures["FakePlayer"].feats[pid].name = "Fake Player Clone (WIP)"

	
	
	end
end

return Moist_Translate

